### ISSUE TITLE
Variable name only replaced once

### ISSUE THREAD

**Issue by silverwind** [golangci/misspell#18] opened 2024-04-18 18:05 UTC
Running with the `-dict` option and passing `commiter,committer`, I see the variable only got replaced once on the first occurence, instead of all occurences in go code. I think it should have replaced on line 248 too here:

<img width="995" alt="Screenshot 2024-04-18 at 20 02 09" src="https://github.com/golangci/misspell/assets/115237/ce741086-efea-4fc5-ad07-8371cc469135">

Is it expected?

Ref: https://github.com/go-gitea/gitea/pull/30573

**Comment by ldez** [comment] 2024-04-18 19:15
First, it's not a new behavior.

I have a minimal reproducible example:

```go
package temp

import (
	"fmt"
	"os"
)

func foo() {
	commiter, _ := os.Open("test") // Detected
	defer commiter.Close() // Not detected

	fmt.Println(commiter) // Detected
	fmt.Println(commiter.Name()) // Not detected
}
```

**Comment by ldez** [comment] 2024-04-18 19:22
It's expected because `smoe.xxx` is not a word `[a-zA-Z0-9]+.

**Comment by ldez** [comment] 2024-04-18 19:28
It's a side effect/false positive of the host parsing.

**Comment by silverwind** [comment] 2024-04-18 19:29
Ah yes, then it's an existing bug that wasn't noticed so far.

**Comment by ldez** [comment] 2024-04-18 21:21
This has been the same behavior for the past 8 years, the goal being to avoid false positives.
Then those false negatives are expected.

**Comment by ldez** [comment] 2024-04-18 21:38
I can improve a bit by following some basic host name rules, but it's impossible to fully fix that without creating a regression.

**Comment by silverwind** [comment] 2024-04-18 23:07
Fine with me, those cases are easy enough to correct manually.

**Comment by ldez** [comment] 2024-04-19 00:30
I improved hostname detection as I explained before.

Now, `defer smoe.Close()` will be detected.
But `defer smoe.close()` is still not detected.

I created a v0.5.1

As the problem cannot be fully fixed, I will close this issue.

**Closed** 2024-04-19 00:31 UTC
Labels: bug, wontfix

**Comment by silverwind** [comment] 2024-04-21 21:16
Thanks, I can confirm it new replaced these missing cases, even without having reset the diff :)
